---
title: "CrowdQCplus on PurpleAir and WeatherUnderground"
format: html
editor: visual
---

## Open RTP data

```{r}
devtools::load_all()
ts <- as.POSIXct("2021-07-01 00:00:00", tz = "UTC")
te <- as.POSIXct("2021-08-01 00:00:00", tz = "UTC")
rtp <- load_rtp_observations(ts, te)
cws <- rtp$cws
ref <- rtp$ref
ref <- ref[which(ref$network != "HEATWATCH"), ]
poly <- rtp$poly
wu <- cws[which(cws$network == "WU"), ]
pa <- cws[which(cws$network == "PA"), ]
```

## CrowdQCplus

CrowdQCplus is applied on both data source separately.

```{r}
wu_qc <- clean_cws(wu)
pa_qc <- clean_cws(pa)
```

```{r}
ts <- as.POSIXct("2021-07-21 00:00:00", tz = "EST")
te <- as.POSIXct("2021-07-27 00:00:00", tz = "EST")
plot_ts(wu_qc, ts, te)
plot_ts(pa_qc, ts, te)
```

Map

```{r}
imp <- terra::rast("../input/rtp_imp.tif") |>
  terra::project("EPSG:4326")
date <- as.POSIXct("2021-07-01 02:00:00", tz = "EST")
map_observations_imp(wu_qc,
                 var = temp,
                 imp = imp,
                 date = date,
                 shape_values = c("WU" = 17),
                 title = "Networks comparison")

map_observations_imp(pa_qc,
                 var = temp,
                 imp = imp,
                 date = date,
                 shape_values = c("PA" = 18),
                 title = "Networks comparison")

pa_qc_corr <- pa_qc
pa_qc_corr$temp <- pa_qc_corr$temp - 5
obs_qc <- rbind(pa_qc_corr, wu_qc)
map_observations_imp(obs_qc,
                 var = temp,
                 imp = imp,
                 date = date,
                 shape_values = c("WU" = 17, "PA" = 18),
                 title = "Networks comparison")
```
