---
title: "Pipeline"
format: html
editor: visual
---

# Brassens pipeline 

The following code generates clean CWS data on the Triangle.

#### Load brassens library

```{r}
devtools::load_all()
```

#### Open Triangle data

```{r}
nc_shp <- paste0("../input/NC_county_boundary/",
                 "North_Carolina_State_and_County_Boundary_Polygons.shp") |>
  terra::vect()
counties <- c("Wake", "Orange", "Durham", "Chatham", "Granville")
rtp_poly <- nc_shp[which(nc_shp$County %in% counties),] 
wake_poly <- nc_shp[which(nc_shp$County %in% "Wake"),] 
ral_inv <- read.csv("../input/weatherunderground/Raleigh_Stations_inventory.csv") |>
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE) 
ral_inv$ts_utc <- as.POSIXct(ral_inv$ts_utc, tz = "UTC")
ral_inv$te_utc <- as.POSIXct(ral_inv$te_utc, tz = "UTC")
```

#### Create configuration list for the pipeline

```{r}
config <- list(
  ts = as.POSIXct("2021-07-22 00:00:00", tz = "UTC"),
  te = as.POSIXct("2021-07-23 23:59:59", tz = "UTC"),
  area = nc_shp,
  wu_inv = ral_inv,
  # following can be NULL ---> load_pa() calls to download_pa()
  pa_file = "./input/rtp/pa_20210720_20210727.csv"
)
```

#### Whole pipeline

```{r}
setwd("../")
ghcnh <- download_ghcnh(config$ts, config$te, config$area)

wu_list <- load_wu(config$ts, config$te, config$area, config$wu_inv) |>
  format_wu() |>
  clean_cws() |>
  calib_cws(ref = ghcnh) 

pa_list <- load_pa(ts = config$ts,
              te = config$te,
              area = config$area,
              storage_file = config$pa_file) |>
  format_pa() |>
  clean_cws() |>
  calib_cws(ref = ghcnh)
```

#### Map cleaned data on RTP on the 2021-07-23 at 6am (local time)

```{r}
wu <- wu_list$obs |>
  sf::st_as_sf(coords = c("lon", "lat"), remove = FALSE)
pa <- pa_list$obs |>
  sf::st_as_sf(coords = c("lon", "lat"), remove = FALSE)
cws <- rbind(wu, pa)
timestamp <- as.POSIXct("2021-07-23 06:00:00", tz = "America/New_York")
imp <- terra::rast("../input/rtp_imp.tif") |>
  terra::project("EPSG:4326")

map <- map_observations_imp(cws,
                     temp_cal,
                     imp,
                     date = timestamp,
                     c("WU" = 17, "PA" = 18),
                     "Weather Underground and PurpleAir")
ggsave(plot = map,
       filename = "../graphs/map_wu_pa_cleaned_am_heatwatch.png",
       width = 7,
       height = 5,
       dpi = 300)
```
